name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jetli/trunk-action@v0.5.1
        with:
          version: "v0.21.14"
      - uses: jetli/wasm-bindgen-action@v0.2.0
      - run: trunk build --release --public-url /${{ github.event.repository.name }}/
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist
